# Generated by Django 5.2.17 on 2026-10-02 16:34

from django.db import migrations, models


def ramener_matieres(apps, schema_editor):
    """Les anciennes discussions n'avaient pas de matière fiable : on les range en maths."""
    Session = apps.get_model("chat", "Session")
    Session.objects.exclude(cours_name__in=["maths", "physique-chimie", "svt"]).update(cours_name="maths")
    for s in Session.objects.all().only("id", "title"):
        if len(s.title) > 80:
            Session.objects.filter(pk=s.pk).update(title=s.title[:80])


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chat_session_userprofile"),
    ]

    operations = [
        migrations.RunPython(ramener_matieres, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["-updated"]},
        ),
        migrations.AddField(
            model_name="chat",
            name="sources",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="session",
            name="guide",
            field=models.BooleanField(
                default=True,
                help_text="Mode « Guide-moi » : Learny pose des questions au lieu de donner la solution.",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="economie_donnees",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="police_lecture",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reduire_animations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="taille_texte",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("auto", "Comme le téléphone"),
                    ("clair", "Clair"),
                    ("sombre", "Sombre"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="cours_name",
            field=models.CharField(default="maths", max_length=40),
        ),
        migrations.AlterField(
            model_name="session",
            name="title",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="genre",
            field=models.CharField(
                blank=True, choices=[("M", "Masculin"), ("F", "Féminin")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("6eme", "6e"),
                    ("5eme", "5e"),
                    ("4eme", "4e"),
                    ("3eme", "3e"),
                ],
                default="3eme",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ville",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="CourseChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matiere", models.CharField(db_index=True, max_length=40)),
                ("source", models.CharField(max_length=200)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("texte", models.TextField()),
                ("embedding", models.JSONField(default=list)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["matiere", "source"],
                        name="chat_course_matiere_1b370b_idx",
                    )
                ],
            },
        ),
    ]
